/*
 * Generated by cue.
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: no version
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package sdk.kubevela.apply_terraform_config.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import sdk.kubevela.apply_terraform_config.model.SourceOneOf;
import sdk.kubevela.apply_terraform_config.model.SourceOneOf1;

import javax.ws.rs.core.GenericType;

import java.io.IOException;
import java.lang.reflect.Type;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.HashMap;
import java.util.Map;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.JsonPrimitive;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonSerializationContext;
import com.google.gson.JsonSerializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;

import sdk.kubevela.apply_terraform_config.JSON;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-10-16T03:49:11.929831Z[Etc/UTC]")
public class Source extends AbstractOpenApiSchema {
    private static final Logger log = Logger.getLogger(Source.class.getName());

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!Source.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'Source' and its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<SourceOneOf> adapterSourceOneOf = gson.getDelegateAdapter(this, TypeToken.get(SourceOneOf.class));
            final TypeAdapter<SourceOneOf1> adapterSourceOneOf1 = gson.getDelegateAdapter(this, TypeToken.get(SourceOneOf1.class));

            return (TypeAdapter<T>) new TypeAdapter<Source>() {
                @Override
                public void write(JsonWriter out, Source value) throws IOException {
                    if (value == null || value.getActualInstance() == null) {
                        elementAdapter.write(out, null);
                        return;
                    }

                    // check if the actual instance is of the type `SourceOneOf`
                    if (value.getActualInstance() instanceof SourceOneOf) {
                        JsonObject obj = adapterSourceOneOf.toJsonTree((SourceOneOf)value.getActualInstance()).getAsJsonObject();
                        elementAdapter.write(out, obj);
                        return;
                    }

                    // check if the actual instance is of the type `SourceOneOf1`
                    if (value.getActualInstance() instanceof SourceOneOf1) {
                        JsonObject obj = adapterSourceOneOf1.toJsonTree((SourceOneOf1)value.getActualInstance()).getAsJsonObject();
                        elementAdapter.write(out, obj);
                        return;
                    }

                    throw new IOException("Failed to serialize as the type doesn't match oneOf schemas: SourceOneOf, SourceOneOf1");
                }

                @Override
                public Source read(JsonReader in) throws IOException {
                    Object deserialized = null;
                    JsonObject jsonObject = elementAdapter.read(in).getAsJsonObject();

                    int match = 0;
                    ArrayList<String> errorMessages = new ArrayList<>();
                    TypeAdapter actualAdapter = elementAdapter;

                    // deserialize SourceOneOf
                    try {
                        // validate the JSON object to see if any exception is thrown
                        SourceOneOf.validateJsonObject(jsonObject);
                        actualAdapter = adapterSourceOneOf;
                        match++;
                        log.log(Level.FINER, "Input data matches schema 'SourceOneOf'");
                    } catch (Exception e) {
                        // deserialization failed, continue
                        errorMessages.add(String.format("Deserialization for SourceOneOf failed with `%s`.", e.getMessage()));
                        log.log(Level.FINER, "Input data does not match schema 'SourceOneOf'", e);
                    }

                    // deserialize SourceOneOf1
                    try {
                        // validate the JSON object to see if any exception is thrown
                        SourceOneOf1.validateJsonObject(jsonObject);
                        actualAdapter = adapterSourceOneOf1;
                        match++;
                        log.log(Level.FINER, "Input data matches schema 'SourceOneOf1'");
                    } catch (Exception e) {
                        // deserialization failed, continue
                        errorMessages.add(String.format("Deserialization for SourceOneOf1 failed with `%s`.", e.getMessage()));
                        log.log(Level.FINER, "Input data does not match schema 'SourceOneOf1'", e);
                    }

                    if (match == 1) {
                        Source ret = new Source();
                        ret.setActualInstance(actualAdapter.fromJsonTree(jsonObject));
                        return ret;
                    }

                    throw new IOException(String.format("Failed deserialization for Source: %d classes match result, expected 1. Detailed failure message for oneOf schemas: %s. JSON: %s", match, errorMessages, jsonObject.toString()));
                }
            }.nullSafe();
        }
    }

    // store a list of schema names defined in oneOf
    public static final Map<String, GenericType> schemas = new HashMap<String, GenericType>();

    public Source() {
        super("oneOf", Boolean.FALSE);
    }

    public Source(SourceOneOf o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public Source(SourceOneOf1 o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    static {
        schemas.put("SourceOneOf", new GenericType<SourceOneOf>() {
        });
        schemas.put("SourceOneOf1", new GenericType<SourceOneOf1>() {
        });
    }

    @Override
    public Map<String, GenericType> getSchemas() {
        return Source.schemas;
    }

    /**
     * Set the instance that matches the oneOf child schema, check
     * the instance parameter is valid against the oneOf child schemas:
     * SourceOneOf, SourceOneOf1
     *
     * It could be an instance of the 'oneOf' schemas.
     * The oneOf child schemas may themselves be a composed schema (allOf, anyOf, oneOf).
     */
    @Override
    public void setActualInstance(Object instance) {
        if (instance instanceof SourceOneOf) {
            super.setActualInstance(instance);
            return;
        }

        if (instance instanceof SourceOneOf1) {
            super.setActualInstance(instance);
            return;
        }

        throw new RuntimeException("Invalid instance type. Must be SourceOneOf, SourceOneOf1");
    }

    /**
     * Get the actual instance, which can be the following:
     * SourceOneOf, SourceOneOf1
     *
     * @return The actual instance (SourceOneOf, SourceOneOf1)
     */
    @Override
    public Object getActualInstance() {
        return super.getActualInstance();
    }

    /**
     * Get the actual instance of `SourceOneOf`. If the actual instance is not `SourceOneOf`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `SourceOneOf`
     * @throws ClassCastException if the instance is not `SourceOneOf`
     */
    public SourceOneOf getSourceOneOf() throws ClassCastException {
        return (SourceOneOf)super.getActualInstance();
    }

    /**
     * Get the actual instance of `SourceOneOf1`. If the actual instance is not `SourceOneOf1`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `SourceOneOf1`
     * @throws ClassCastException if the instance is not `SourceOneOf1`
     */
    public SourceOneOf1 getSourceOneOf1() throws ClassCastException {
        return (SourceOneOf1)super.getActualInstance();
    }


 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to Source
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
    // validate oneOf schemas one by one
    int validCount = 0;
    ArrayList<String> errorMessages = new ArrayList<>();
    // validate the json string with SourceOneOf
    try {
      SourceOneOf.validateJsonObject(jsonObj);
      validCount++;
    } catch (Exception e) {
      errorMessages.add(String.format("Deserialization for SourceOneOf failed with `%s`.", e.getMessage()));
      // continue to the next one
    }
    // validate the json string with SourceOneOf1
    try {
      SourceOneOf1.validateJsonObject(jsonObj);
      validCount++;
    } catch (Exception e) {
      errorMessages.add(String.format("Deserialization for SourceOneOf1 failed with `%s`.", e.getMessage()));
      // continue to the next one
    }
    if (validCount != 1) {
      throw new IOException(String.format("The JSON string is invalid for Source with oneOf schemas: SourceOneOf, SourceOneOf1. %d class(es) match the result, expected 1. Detailed failure message for oneOf schemas: %s. JSON: %s", validCount, errorMessages, jsonObj.toString()));
    }
  }

 /**
  * Create an instance of Source given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of Source
  * @throws IOException if the JSON string is invalid with respect to Source
  */
  public static Source fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, Source.class);
  }

 /**
  * Convert an instance of Source to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

