/*
 * Generated by cue.
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: no version
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package sdk.kubevela.affinity.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import sdk.kubevela.affinity.model.PodAffinityTerm;
import sdk.kubevela.affinity.model.Preferred1;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import sdk.kubevela.affinity.JSON;

/**
 * Specify the pod affinity scheduling rules
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-10-16T03:49:01.416288Z[Etc/UTC]")
public class PodAffinity {
  public static final String SERIALIZED_NAME_PREFERRED = "preferred";
  @SerializedName(SERIALIZED_NAME_PREFERRED)
  private List<Preferred1> preferred = null;

  public static final String SERIALIZED_NAME_REQUIRED = "required";
  @SerializedName(SERIALIZED_NAME_REQUIRED)
  private List<PodAffinityTerm> required = null;

  public PodAffinity() {
  }

  public PodAffinity preferred(List<Preferred1> preferred) {
    
    this.preferred = preferred;
    return this;
  }

  public PodAffinity addPreferredItem(Preferred1 preferredItem) {
    if (this.preferred == null) {
      this.preferred = new ArrayList<>();
    }
    this.preferred.add(preferredItem);
    return this;
  }

   /**
   * Specify the preferred during scheduling ignored during execution
   * @return preferred
  **/
  @javax.annotation.Nullable

  public List<Preferred1> getPreferred() {
    return preferred;
  }


  public void setPreferred(List<Preferred1> preferred) {
    this.preferred = preferred;
  }


  public PodAffinity required(List<PodAffinityTerm> required) {
    
    this.required = required;
    return this;
  }

  public PodAffinity addRequiredItem(PodAffinityTerm requiredItem) {
    if (this.required == null) {
      this.required = new ArrayList<>();
    }
    this.required.add(requiredItem);
    return this;
  }

   /**
   * Specify the required during scheduling ignored during execution
   * @return required
  **/
  @javax.annotation.Nullable

  public List<PodAffinityTerm> getRequired() {
    return required;
  }


  public void setRequired(List<PodAffinityTerm> required) {
    this.required = required;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PodAffinity podAffinity = (PodAffinity) o;
    return Objects.equals(this.preferred, podAffinity.preferred) &&
        Objects.equals(this.required, podAffinity.required);
  }

  @Override
  public int hashCode() {
    return Objects.hash(preferred, required);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PodAffinity {\n");
    sb.append("    preferred: ").append(toIndentedString(preferred)).append("\n");
    sb.append("    required: ").append(toIndentedString(required)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("preferred");
    openapiFields.add("required");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to PodAffinity
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!PodAffinity.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in PodAffinity is not found in the empty JSON string", PodAffinity.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!PodAffinity.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `PodAffinity` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
      if (jsonObj.get("preferred") != null && !jsonObj.get("preferred").isJsonNull()) {
        JsonArray jsonArraypreferred = jsonObj.getAsJsonArray("preferred");
        if (jsonArraypreferred != null) {
          // ensure the json data is an array
          if (!jsonObj.get("preferred").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `preferred` to be an array in the JSON string but got `%s`", jsonObj.get("preferred").toString()));
          }

          // validate the optional field `preferred` (array)
          for (int i = 0; i < jsonArraypreferred.size(); i++) {
            Preferred1.validateJsonObject(jsonArraypreferred.get(i).getAsJsonObject());
          };
        }
      }
      if (jsonObj.get("required") != null && !jsonObj.get("required").isJsonNull()) {
        JsonArray jsonArrayrequired = jsonObj.getAsJsonArray("required");
        if (jsonArrayrequired != null) {
          // ensure the json data is an array
          if (!jsonObj.get("required").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `required` to be an array in the JSON string but got `%s`", jsonObj.get("required").toString()));
          }

          // validate the optional field `required` (array)
          for (int i = 0; i < jsonArrayrequired.size(); i++) {
            PodAffinityTerm.validateJsonObject(jsonArrayrequired.get(i).getAsJsonObject());
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!PodAffinity.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'PodAffinity' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<PodAffinity> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(PodAffinity.class));

       return (TypeAdapter<T>) new TypeAdapter<PodAffinity>() {
           @Override
           public void write(JsonWriter out, PodAffinity value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public PodAffinity read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of PodAffinity given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of PodAffinity
  * @throws IOException if the JSON string is invalid with respect to PodAffinity
  */
  public static PodAffinity fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, PodAffinity.class);
  }

 /**
  * Convert an instance of PodAffinity to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

