/*
 * Generated by cue.
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: no version
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package sdk.kubevela.autoscale.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import sdk.kubevela.autoscale.model.Cron;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import sdk.kubevela.autoscale.JSON;

/**
 * AutoscaleSpec
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-10-16T03:49:13.648143Z[Etc/UTC]")
public class AutoscaleSpec {
  public static final String SERIALIZED_NAME_CPU_PERCENT = "cpuPercent";
  @SerializedName(SERIALIZED_NAME_CPU_PERCENT)
  private Integer cpuPercent;

  public static final String SERIALIZED_NAME_CRON = "cron";
  @SerializedName(SERIALIZED_NAME_CRON)
  private Cron cron;

  public static final String SERIALIZED_NAME_MAX = "max";
  @SerializedName(SERIALIZED_NAME_MAX)
  private Integer max;

  public static final String SERIALIZED_NAME_MIN = "min";
  @SerializedName(SERIALIZED_NAME_MIN)
  private Integer min;

  public AutoscaleSpec() {
  }

  public AutoscaleSpec cpuPercent(Integer cpuPercent) {
    
    this.cpuPercent = cpuPercent;
    return this;
  }

   /**
   * Specify the value for CPU utilization, like 80, which means 80% +alias&#x3D;cpu-percent
   * @return cpuPercent
  **/
  @javax.annotation.Nullable

  public Integer getCpuPercent() {
    return cpuPercent;
  }


  public void setCpuPercent(Integer cpuPercent) {
    this.cpuPercent = cpuPercent;
  }


  public AutoscaleSpec cron(Cron cron) {
    
    this.cron = cron;
    return this;
  }

   /**
   * Get cron
   * @return cron
  **/
  @javax.annotation.Nullable

  public Cron getCron() {
    return cron;
  }


  public void setCron(Cron cron) {
    this.cron = cron;
  }


  public AutoscaleSpec max(Integer max) {
    
    this.max = max;
    return this;
  }

   /**
   * Maximal replicas of the workload
   * @return max
  **/
  @javax.annotation.Nonnull

  public Integer getMax() {
    return max;
  }


  public void setMax(Integer max) {
    this.max = max;
  }


  public AutoscaleSpec min(Integer min) {
    
    this.min = min;
    return this;
  }

   /**
   * Minimal replicas of the workload
   * @return min
  **/
  @javax.annotation.Nonnull

  public Integer getMin() {
    return min;
  }


  public void setMin(Integer min) {
    this.min = min;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AutoscaleSpec autoscaleSpec = (AutoscaleSpec) o;
    return Objects.equals(this.cpuPercent, autoscaleSpec.cpuPercent) &&
        Objects.equals(this.cron, autoscaleSpec.cron) &&
        Objects.equals(this.max, autoscaleSpec.max) &&
        Objects.equals(this.min, autoscaleSpec.min);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cpuPercent, cron, max, min);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AutoscaleSpec {\n");
    sb.append("    cpuPercent: ").append(toIndentedString(cpuPercent)).append("\n");
    sb.append("    cron: ").append(toIndentedString(cron)).append("\n");
    sb.append("    max: ").append(toIndentedString(max)).append("\n");
    sb.append("    min: ").append(toIndentedString(min)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("cpuPercent");
    openapiFields.add("cron");
    openapiFields.add("max");
    openapiFields.add("min");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("max");
    openapiRequiredFields.add("min");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to AutoscaleSpec
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!AutoscaleSpec.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in AutoscaleSpec is not found in the empty JSON string", AutoscaleSpec.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!AutoscaleSpec.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `AutoscaleSpec` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : AutoscaleSpec.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      // validate the optional field `cron`
      if (jsonObj.get("cron") != null && !jsonObj.get("cron").isJsonNull()) {
        Cron.validateJsonObject(jsonObj.getAsJsonObject("cron"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!AutoscaleSpec.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'AutoscaleSpec' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<AutoscaleSpec> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(AutoscaleSpec.class));

       return (TypeAdapter<T>) new TypeAdapter<AutoscaleSpec>() {
           @Override
           public void write(JsonWriter out, AutoscaleSpec value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public AutoscaleSpec read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of AutoscaleSpec given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of AutoscaleSpec
  * @throws IOException if the JSON string is invalid with respect to AutoscaleSpec
  */
  public static AutoscaleSpec fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, AutoscaleSpec.class);
  }

 /**
  * Convert an instance of AutoscaleSpec to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

