/*
 * Generated by cue.
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: no version
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package sdk.kubevela.notification.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import sdk.kubevela.notification.model.Dingding;
import sdk.kubevela.notification.model.Email;
import sdk.kubevela.notification.model.Lark;
import sdk.kubevela.notification.model.Slack;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import sdk.kubevela.notification.JSON;

/**
 * NotificationSpec
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-10-16T03:50:22.794956Z[Etc/UTC]")
public class NotificationSpec {
  public static final String SERIALIZED_NAME_DINGDING = "dingding";
  @SerializedName(SERIALIZED_NAME_DINGDING)
  private Dingding dingding;

  public static final String SERIALIZED_NAME_EMAIL = "email";
  @SerializedName(SERIALIZED_NAME_EMAIL)
  private Email email;

  public static final String SERIALIZED_NAME_LARK = "lark";
  @SerializedName(SERIALIZED_NAME_LARK)
  private Lark lark;

  public static final String SERIALIZED_NAME_SLACK = "slack";
  @SerializedName(SERIALIZED_NAME_SLACK)
  private Slack slack;

  public NotificationSpec() {
  }

  public NotificationSpec dingding(Dingding dingding) {
    
    this.dingding = dingding;
    return this;
  }

   /**
   * Get dingding
   * @return dingding
  **/
  @javax.annotation.Nullable

  public Dingding getDingding() {
    return dingding;
  }


  public void setDingding(Dingding dingding) {
    this.dingding = dingding;
  }


  public NotificationSpec email(Email email) {
    
    this.email = email;
    return this;
  }

   /**
   * Get email
   * @return email
  **/
  @javax.annotation.Nullable

  public Email getEmail() {
    return email;
  }


  public void setEmail(Email email) {
    this.email = email;
  }


  public NotificationSpec lark(Lark lark) {
    
    this.lark = lark;
    return this;
  }

   /**
   * Get lark
   * @return lark
  **/
  @javax.annotation.Nullable

  public Lark getLark() {
    return lark;
  }


  public void setLark(Lark lark) {
    this.lark = lark;
  }


  public NotificationSpec slack(Slack slack) {
    
    this.slack = slack;
    return this;
  }

   /**
   * Get slack
   * @return slack
  **/
  @javax.annotation.Nullable

  public Slack getSlack() {
    return slack;
  }


  public void setSlack(Slack slack) {
    this.slack = slack;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NotificationSpec notificationSpec = (NotificationSpec) o;
    return Objects.equals(this.dingding, notificationSpec.dingding) &&
        Objects.equals(this.email, notificationSpec.email) &&
        Objects.equals(this.lark, notificationSpec.lark) &&
        Objects.equals(this.slack, notificationSpec.slack);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dingding, email, lark, slack);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NotificationSpec {\n");
    sb.append("    dingding: ").append(toIndentedString(dingding)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    lark: ").append(toIndentedString(lark)).append("\n");
    sb.append("    slack: ").append(toIndentedString(slack)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("dingding");
    openapiFields.add("email");
    openapiFields.add("lark");
    openapiFields.add("slack");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to NotificationSpec
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!NotificationSpec.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in NotificationSpec is not found in the empty JSON string", NotificationSpec.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!NotificationSpec.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `NotificationSpec` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
      // validate the optional field `dingding`
      if (jsonObj.get("dingding") != null && !jsonObj.get("dingding").isJsonNull()) {
        Dingding.validateJsonObject(jsonObj.getAsJsonObject("dingding"));
      }
      // validate the optional field `email`
      if (jsonObj.get("email") != null && !jsonObj.get("email").isJsonNull()) {
        Email.validateJsonObject(jsonObj.getAsJsonObject("email"));
      }
      // validate the optional field `lark`
      if (jsonObj.get("lark") != null && !jsonObj.get("lark").isJsonNull()) {
        Lark.validateJsonObject(jsonObj.getAsJsonObject("lark"));
      }
      // validate the optional field `slack`
      if (jsonObj.get("slack") != null && !jsonObj.get("slack").isJsonNull()) {
        Slack.validateJsonObject(jsonObj.getAsJsonObject("slack"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!NotificationSpec.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'NotificationSpec' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<NotificationSpec> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(NotificationSpec.class));

       return (TypeAdapter<T>) new TypeAdapter<NotificationSpec>() {
           @Override
           public void write(JsonWriter out, NotificationSpec value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public NotificationSpec read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of NotificationSpec given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of NotificationSpec
  * @throws IOException if the JSON string is invalid with respect to NotificationSpec
  */
  public static NotificationSpec fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, NotificationSpec.class);
  }

 /**
  * Convert an instance of NotificationSpec to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

